Failure # 1 (occurred at 2022-12-05_13-03-03)
Traceback (most recent call last):
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\tune\execution\ray_trial_executor.py", line 1050, in get_next_executor_event
    future_result = ray.get(ready_future)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\_private\client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\_private\worker.py", line 2291, in get
    raise value
ray.exceptions.RayActorError: The actor died because of an error raised in its creation task, [36mray::PPO.__init__()[39m (pid=19352, ip=127.0.0.1, repr=PPO)
  File "python\ray\_raylet.pyx", line 859, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 863, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 810, in ray._raylet.execute_task.function_executor
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\_private\function_manager.py", line 674, in actor_method_executor
    return method(__ray_actor, *args, **kwargs)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 414, in __init__
    super().__init__(config=config, logger_creator=logger_creator, **kwargs)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\tune\trainable\trainable.py", line 161, in __init__
    self.setup(copy.deepcopy(self.config))
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 451, in setup
    self.validate_config(self.config)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\util\tracing\tracing_helper.py", line 466, in _resume_span
    return method(self, *_args, **_kwargs)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\rllib\algorithms\ppo\ppo.py", line 308, in validate_config
    super().validate_config(config)
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\rllib\algorithms\algorithm.py", line 2519, in validate_config
    deprecation_warning(
  File "G:\PycharmProject\rllib_examples\venv\lib\site-packages\ray\rllib\utils\deprecation.py", line 43, in deprecation_warning
    raise DeprecationWarning(msg)
DeprecationWarning: `evaluation_num_episodes` has been deprecated. Use ``evaluation_duration` and `evaluation_duration_unit=episodes`` instead.

